name: Hugo Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: versioned_docs
  hugo-env:
    required: false
    description: Environment variable
    default: public

runs:
  using: "composite"
  steps:
    - name: Generate Versioned Documentation
      run: |
        cd docs
        ../scripts/generate.sh origin $THIS_BRANCH $KEEP_MASTER
        - if [ "$THIS_BRANCH" != "master" ] ; then git checkout master ; fi
        - |
          cat << EOF
          HUGO_ENV=$HUGO_ENV
          THIS_BRANCH=$THIS_BRANCH
          KEEP_MASTER=$KEEP_MASTER
          EXTRA_HUGO_ARGS=$EXTRA_HUGO_ARGS
          EOF
        - npm install
        - hugo version
        - hugo --minify ${BASE_URL:+--baseURL $BASE_URL} $EXTRA_HUGO_ARGS
      shell: bash 
