name: Hugo Versioned Docs
on:
  workflow_dispatch:
jobs:
  hugo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Generate Versioned Docs
        uses: ./.github/actions/hugo-build-versioned-action
      - name: htmltest
        run: |
          scripts/htmltest -c docs/.htmltest.yml docs/public
