# Keep Hugo docs build to verify documentation can be built also on localhost with correct links
name: Hugo docs
on:
  workflow_dispatch:
jobs:
  hugo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Hugo Build
        uses: ./.github/actions/hugo-build-action
      - name: htmltest
        run: |
          scripts/htmltest -c docs/.htmltest.yml docs/public
